---
- name: Copy groovy scripts to jenkins groovy directory
  template:
    src: "{{ item }}"
    dest: "{{ jenkins_home }}/init.groovy.d/google-oauth-{{ item.rstrip('.j2') }}"
    owner: "{{ jenkins_process_user }}"
    group: "{{ jenkins_process_group }}"
    mode: 0775
  with_items: "{{ jenkins_security_init_scripts }}"

- name: Force Jenkins restart
  service: name=jenkins state=restarted

- name: Give some time for Jenkins to restart and apply the init scripts
  uri:
    url: "http://{{ jenkins_host }}:{{ jenkins_port }}/"
    status_code: [200, 403]
    timeout: 2
  register: result
  until: result.status == 200 or result.status == 403
  retries: 12
  delay: 4

- name: Remove Jenkins security init scripts after restart
  file:
    path: "{{ jenkins_home }}/init.groovy.d/google-oauth-{{ item.rstrip('.j2') }}"
    state: absent
  with_items: "{{ jenkins_security_init_scripts }}"
